### ISSUE TITLE
fcc waves crash gsa

### ISSUE THREAD

**Issue by notgeorge** [vm-wylbur-pi/fof_tests#4]
when running waves from the FCC the field parameter isn't being set, resulting in an unrecoverable gsa crash.

Received message, topic='game-control/runGame/CircularColorWave', content='b'180,300,450,0,600''
Command is runGame/CircularColorWave['180', '300', '450', '0', '600']
Traceback (most recent call last):
  File "gsa/main.py", line 88, in <module>
    mqtt_client.loop()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1120, in loop
    return self._loop(timeout)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/app/gsa/mqtt.py", line 23, in on_message
    HandleMQTTMessage(message, gameState)
  File "/app/gsa/mqtt.py", line 68, in HandleMQTTMessage
    wave = games.CircularColorWave.randomInstance()
TypeError: randomInstance() missing 1 required positional argument: 'field'

**Comment by notgeorge** [comment]
needed to pass gamestate.field to commands in mqtt

   if command == "runGame/CircularColorWave":
        wave = games.CircularColorWave.randomInstance(gameState.field)
