### ISSUE TITLE
GSA Bugs from Dress Rehersal Test

### ISSUE THREAD

**Issue by notgeorge** [vm-wylbur-pi/fof_tests#5]
gsa bugs when running without the VA running as well seems to cause crashes of the gsa.

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    gameState.people.removePeopleNotSeenForAWhile()
  File "/app/gsa/person.py", line 77, in removePeopleNotSeenForAWhile
    time_since_last_seen = now - self.people[name].last_seen
TypeError: unsupported operand type(s) for -: 'float' and 'str'

running a wave game from the FCC causes an exception and crashes.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/app/gsa/mqtt.py", line 32, in on_message
    HandleMQTTMessage(message, gameState)
  File "/app/gsa/mqtt.py", line 59, in HandleMQTTMessage
    HandleGameControlCommand(message, gameState)
  File "/app/gsa/mqtt.py", line 77, in HandleGameControlCommand
    gameState.clearStatefulGames()
  File "/app/gsa/game_state.py", line 29, in clearStatefulGames
    game.stop(self)
  File "/app/gsa/games/game.py", line 33, in stop
    raise NotImplementedError

**Comment by pegleg-dragon** [comment]
Commit 5e81b2f solved the 2nd issue.

**Comment by pegleg-dragon** [comment]
Commit 89eaf63760a8679c4759f1dfdece93c359bb97d5 solved the 1st issue.
